name: Reminder Job

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: python reminder_system.py
        env:
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
